// const {john, peter} = require('./4-names')
// console.log(john + peter)
// const sayHi = require('./5-utils')
// const data = require('./6-alternative-flavour')
// console.log(data)

// sayHi('Susan')
// sayHi(john)
// sayHi(peter)
require('./7-mind-grenade')
